### ISSUE TITLE
Production downloadable link is missing 

### ISSUE THREAD

**Issue by letientai299** [jgallen23/toc#66]
Link to download production  and development file on the github pages are missing due to `dist` folder is removed. 

```
https://raw.githubusercontent.com/jgallen23/toc/master/dist/toc.min.js
```

Could you please add new links or summit this library into cdnjs/jsdelivery?

**Comment by KeJunMao** [comment]
here

**Comment by wsw70** [comment]
The link is still dead, the issue should not be closed.

**Comment by jgallen23** [comment]
https://raw.githubusercontent.com/jgallen23/toc/0.3.2/dist/toc.min.js

**Comment by jamiejackson** [comment]
That gave me mime type problems: `Refused to execute script from 'https://raw.githubusercontent.com/jgallen23/toc/0.3.2/dist/toc.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

This works better for me: https://cdn.rawgit.com/jgallen23/toc/0.3.2/dist/toc.min.js

**Comment by jgallen23** [comment]
thanks @jamiejackson
